import { Container, Header } from '@/common'
import { Metadata } from 'next'
import { ReactNode, Suspense } from 'react'

export const metadata: Metadata = {
  title: 'Reack Pizza | Корзина',
  description: 'Generated by create next app',
}

export default function CheckoutLayout({ children }: { children: ReactNode }) {
  return (
    <main className={'min-h-screen bg-[#F4F1EE]'}>
      <Container>
        <Suspense>
          <Header hasSearch={false} hasCart={false} className={'border-b-gray-200'} />
        </Suspense>
        {children}
      </Container>
    </main>
  )
}
